/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppParentsRouteImport } from './routes/_app.parents'
import { Route as AppInstructorsRouteImport } from './routes/_app.instructors'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppCoursesRouteImport } from './routes/_app.courses'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppStudentsIdRouteImport } from './routes/_app.students.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppParentsRoute = AppParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorsRoute = AppInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/courses': typeof AppCoursesRoute
  '/finance': typeof AppFinanceRoute
  '/instructors': typeof AppInstructorsRoute
  '/parents': typeof AppParentsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/students/$id': typeof AppStudentsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/courses': typeof AppCoursesRoute
  '/finance': typeof AppFinanceRoute
  '/instructors': typeof AppInstructorsRoute
  '/parents': typeof AppParentsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/': typeof AppIndexRoute
  '/students/$id': typeof AppStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/courses': typeof AppCoursesRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/instructors': typeof AppInstructorsRoute
  '/_app/parents': typeof AppParentsRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/students/$id': typeof AppStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/courses'
    | '/finance'
    | '/instructors'
    | '/parents'
    | '/students'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendance'
    | '/courses'
    | '/finance'
    | '/instructors'
    | '/parents'
    | '/students'
    | '/'
    | '/students/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/attendance'
    | '/_app/courses'
    | '/_app/finance'
    | '/_app/instructors'
    | '/_app/parents'
    | '/_app/students'
    | '/_app/'
    | '/_app/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parents': {
      id: '/_app/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AppParentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instructors': {
      id: '/_app/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof AppInstructorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$id': {
      id: '/_app/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsIdRoute: typeof AppStudentsIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsIdRoute: AppStudentsIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInstructorsRoute: typeof AppInstructorsRoute
  AppParentsRoute: typeof AppParentsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInstructorsRoute: AppInstructorsRoute,
  AppParentsRoute: AppParentsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
