/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScheduleRouteImport } from './routes/_app.schedule'
import { Route as AppReviewsRouteImport } from './routes/_app.reviews'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProgramsRouteImport } from './routes/_app.programs'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppParentsRouteImport } from './routes/_app.parents'
import { Route as AppLessonsRouteImport } from './routes/_app.lessons'
import { Route as AppInstructorsRouteImport } from './routes/_app.instructors'
import { Route as AppFundRequestsRouteImport } from './routes/_app.fund-requests'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppDiceInstitutionsRouteImport } from './routes/_app.dice-institutions'
import { Route as AppCoursesRouteImport } from './routes/_app.courses'
import { Route as AppChildrenRouteImport } from './routes/_app.children'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAssessmentsRouteImport } from './routes/_app.assessments'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as PortfolioStudentIdRouteImport } from './routes/portfolio.student.$id'
import { Route as PortfolioGalleryBranchRouteImport } from './routes/portfolio.gallery.$branch'
import { Route as AppStudentsIdRouteImport } from './routes/_app.students.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsRoute = AppProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppParentsRoute = AppParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorsRoute = AppInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AppRoute,
} as any)
const AppFundRequestsRoute = AppFundRequestsRouteImport.update({
  id: '/fund-requests',
  path: '/fund-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDiceInstitutionsRoute = AppDiceInstitutionsRouteImport.update({
  id: '/dice-institutions',
  path: '/dice-institutions',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenRoute = AppChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const PortfolioStudentIdRoute = PortfolioStudentIdRouteImport.update({
  id: '/portfolio/student/$id',
  path: '/portfolio/student/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioGalleryBranchRoute = PortfolioGalleryBranchRouteImport.update({
  id: '/portfolio/gallery/$branch',
  path: '/portfolio/gallery/$branch',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assessments': typeof AppAssessmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/children': typeof AppChildrenRoute
  '/courses': typeof AppCoursesRoute
  '/dice-institutions': typeof AppDiceInstitutionsRoute
  '/finance': typeof AppFinanceRoute
  '/fund-requests': typeof AppFundRequestsRoute
  '/instructors': typeof AppInstructorsRoute
  '/lessons': typeof AppLessonsRoute
  '/parents': typeof AppParentsRoute
  '/payroll': typeof AppPayrollRoute
  '/portfolio': typeof AppPortfolioRoute
  '/programs': typeof AppProgramsRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/reviews': typeof AppReviewsRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/timetable': typeof AppTimetableRoute
  '/students/$id': typeof AppStudentsIdRoute
  '/portfolio/gallery/$branch': typeof PortfolioGalleryBranchRoute
  '/portfolio/student/$id': typeof PortfolioStudentIdRoute
}
export interface FileRoutesByTo {
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assessments': typeof AppAssessmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/children': typeof AppChildrenRoute
  '/courses': typeof AppCoursesRoute
  '/dice-institutions': typeof AppDiceInstitutionsRoute
  '/finance': typeof AppFinanceRoute
  '/fund-requests': typeof AppFundRequestsRoute
  '/instructors': typeof AppInstructorsRoute
  '/lessons': typeof AppLessonsRoute
  '/parents': typeof AppParentsRoute
  '/payroll': typeof AppPayrollRoute
  '/portfolio': typeof AppPortfolioRoute
  '/programs': typeof AppProgramsRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/reviews': typeof AppReviewsRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/timetable': typeof AppTimetableRoute
  '/': typeof AppIndexRoute
  '/students/$id': typeof AppStudentsIdRoute
  '/portfolio/gallery/$branch': typeof PortfolioGalleryBranchRoute
  '/portfolio/student/$id': typeof PortfolioStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/assessments': typeof AppAssessmentsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/children': typeof AppChildrenRoute
  '/_app/courses': typeof AppCoursesRoute
  '/_app/dice-institutions': typeof AppDiceInstitutionsRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/fund-requests': typeof AppFundRequestsRoute
  '/_app/instructors': typeof AppInstructorsRoute
  '/_app/lessons': typeof AppLessonsRoute
  '/_app/parents': typeof AppParentsRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/programs': typeof AppProgramsRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/reviews': typeof AppReviewsRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/': typeof AppIndexRoute
  '/_app/students/$id': typeof AppStudentsIdRoute
  '/portfolio/gallery/$branch': typeof PortfolioGalleryBranchRoute
  '/portfolio/student/$id': typeof PortfolioStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feedback'
    | '/login'
    | '/account'
    | '/announcements'
    | '/assessments'
    | '/attendance'
    | '/audit'
    | '/children'
    | '/courses'
    | '/dice-institutions'
    | '/finance'
    | '/fund-requests'
    | '/instructors'
    | '/lessons'
    | '/parents'
    | '/payroll'
    | '/portfolio'
    | '/programs'
    | '/projects'
    | '/reports'
    | '/reviews'
    | '/schedule'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/students/$id'
    | '/portfolio/gallery/$branch'
    | '/portfolio/student/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/feedback'
    | '/login'
    | '/account'
    | '/announcements'
    | '/assessments'
    | '/attendance'
    | '/audit'
    | '/children'
    | '/courses'
    | '/dice-institutions'
    | '/finance'
    | '/fund-requests'
    | '/instructors'
    | '/lessons'
    | '/parents'
    | '/payroll'
    | '/portfolio'
    | '/programs'
    | '/projects'
    | '/reports'
    | '/reviews'
    | '/schedule'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/'
    | '/students/$id'
    | '/portfolio/gallery/$branch'
    | '/portfolio/student/$id'
  id:
    | '__root__'
    | '/_app'
    | '/feedback'
    | '/login'
    | '/_app/account'
    | '/_app/announcements'
    | '/_app/assessments'
    | '/_app/attendance'
    | '/_app/audit'
    | '/_app/children'
    | '/_app/courses'
    | '/_app/dice-institutions'
    | '/_app/finance'
    | '/_app/fund-requests'
    | '/_app/instructors'
    | '/_app/lessons'
    | '/_app/parents'
    | '/_app/payroll'
    | '/_app/portfolio'
    | '/_app/programs'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/reviews'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/timetable'
    | '/_app/'
    | '/_app/students/$id'
    | '/portfolio/gallery/$branch'
    | '/portfolio/student/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  PortfolioGalleryBranchRoute: typeof PortfolioGalleryBranchRoute
  PortfolioStudentIdRoute: typeof PortfolioStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reviews': {
      id: '/_app/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs': {
      id: '/_app/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AppProgramsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parents': {
      id: '/_app/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AppParentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons': {
      id: '/_app/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instructors': {
      id: '/_app/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof AppInstructorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fund-requests': {
      id: '/_app/fund-requests'
      path: '/fund-requests'
      fullPath: '/fund-requests'
      preLoaderRoute: typeof AppFundRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dice-institutions': {
      id: '/_app/dice-institutions'
      path: '/dice-institutions'
      fullPath: '/dice-institutions'
      preLoaderRoute: typeof AppDiceInstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/children': {
      id: '/_app/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AppChildrenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessments': {
      id: '/_app/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/portfolio/student/$id': {
      id: '/portfolio/student/$id'
      path: '/portfolio/student/$id'
      fullPath: '/portfolio/student/$id'
      preLoaderRoute: typeof PortfolioStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/gallery/$branch': {
      id: '/portfolio/gallery/$branch'
      path: '/portfolio/gallery/$branch'
      fullPath: '/portfolio/gallery/$branch'
      preLoaderRoute: typeof PortfolioGalleryBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/students/$id': {
      id: '/_app/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsIdRoute: typeof AppStudentsIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsIdRoute: AppStudentsIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditRoute: typeof AppAuditRoute
  AppChildrenRoute: typeof AppChildrenRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppDiceInstitutionsRoute: typeof AppDiceInstitutionsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFundRequestsRoute: typeof AppFundRequestsRoute
  AppInstructorsRoute: typeof AppInstructorsRoute
  AppLessonsRoute: typeof AppLessonsRoute
  AppParentsRoute: typeof AppParentsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProgramsRoute: typeof AppProgramsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppTimetableRoute: typeof AppTimetableRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditRoute: AppAuditRoute,
  AppChildrenRoute: AppChildrenRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppDiceInstitutionsRoute: AppDiceInstitutionsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFundRequestsRoute: AppFundRequestsRoute,
  AppInstructorsRoute: AppInstructorsRoute,
  AppLessonsRoute: AppLessonsRoute,
  AppParentsRoute: AppParentsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProgramsRoute: AppProgramsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReportsRoute: AppReportsRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppTimetableRoute: AppTimetableRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  PortfolioGalleryBranchRoute: PortfolioGalleryBranchRoute,
  PortfolioStudentIdRoute: PortfolioStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
